### ISSUE TITLE
uk.co.real_logic.fix_gateway.system_tests.ClusteredGatewaySystemTest > shouldExchangeMessagesInCluster FAILED

### ISSUE THREAD

**Issue by mjpt777** [real-logic/artio#129]
uk.co.real_logic.fix_gateway.system_tests.ClusteredGatewaySystemTest > shouldExchangeMessagesInCluster FAILED
    For file: session_id_buffer: arrays first differed at element [20]; expected:<-1> but was:<-51>
        at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:55)
        at org.junit.Assert.internalArrayEquals(Assert.java:532)
        at org.junit.Assert.assertArrayEquals(Assert.java:341)
        at uk.co.real_logic.fix_gateway.system_tests.ClusteredGatewaySystemTest.assertFilesEqual(ClusteredGatewaySystemTest.java:410)
        at uk.co.real_logic.fix_gateway.system_tests.ClusteredGatewaySystemTest.lambda$assertAllClusterNodesHaveSameIndexFiles$13(ClusteredGatewaySystemTest.java:377)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.SliceOps$1$1.accept(SliceOps.java:204)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at uk.co.real_logic.fix_gateway.system_tests.ClusteredGatewaySystemTest.assertAllClusterNodesHaveSameIndexFiles(ClusteredGatewaySystemTest.java:372)
        at uk.co.real_logic.fix_gateway.system_tests.ClusteredGatewaySystemTest.shouldExchangeMessagesInCluster(ClusteredGatewaySystemTest.java:163)

        Caused by:
        java.lang.AssertionError: expected:<-1> but was:<-51>
            at org.junit.Assert.fail(Assert.java:88)
            at org.junit.Assert.failNotEquals(Assert.java:834)
            at org.junit.Assert.assertEquals(Assert.java:118)
            at org.junit.Assert.assertEquals(Assert.java:144)
            at org.junit.internal.ExactComparisonCriteria.assertElementsEqual(ExactComparisonCriteria.java:8)
            at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:53)
            ... 15 more

**Comment by RichardWarburton** [comment]
Closed, removed old clustering.
