### ISSUE TITLE
FIX server throw exception when the FIX client become slow consumer.

### ISSUE THREAD

**Issue by guoguanglei** [real-logic/artio#191]
I use 8 FIX clients to connect a FIX server.
Only one FIX client has order->fill report flow.
When that FIX client send massive orders and become really slow when processing Fill report,
**the FIX server will throw below exception continuously.**

```JAVA
java.lang.IllegalArgumentException: newPosition of 1426936960 out of range 46929728-114038592
        at io.aeron.Image.validatePosition(Image.java:664)
        at io.aeron.Image.position(Image.java:224)
        at uk.co.real_logic.artio.engine.framer.SlowPeeker.peek(SlowPeeker.java:42)
        at uk.co.real_logic.artio.engine.framer.SubscriptionSlowPeeker$LibrarySlowPeeker.peek(SubscriptionSlowPeeker.java:100)
        at uk.co.real_logic.artio.engine.framer.SubscriptionSlowPeeker.peek(SubscriptionSlowPeeker.java:43)
        at uk.co.real_logic.artio.engine.framer.Framer.sendOutboundMessages(Framer.java:349)
        at uk.co.real_logic.artio.engine.framer.Framer.doWork(Framer.java:299)
        at org.agrona.concurrent.AgentRunner.doDutyCycle(AgentRunner.java:268)
        at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:161)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by RichardWarburton** [comment]
Thanks for the bug report. Do you know roughly how big the messages are that cause this exception?

**Comment by RichardWarburton** [comment]
More specifically - are they > 67108864 bytes?

**Comment by guoguanglei** [comment]
I sent 250K orders, every order is around 194 bytes.

Example order:
8=FIX.4.2|9=172|35=D|50=XXX|34=5|49=CCCCCCCCC|56=DDDDD|52=20181104-11:45:27.583|11=103MKD1MKD|21=2|40=2|54=1|55=INST|48=INST|38=200|44=1.0|59=0|1=AAAAAAAAAAAAAAAAAAA|0=AAAAAAAAAAAAAAAAAAA|10=225

**Comment by RichardWarburton** [comment]
Do you know what size the Aeron term buffers are set to in this case?

**Comment by RichardWarburton** [comment]
I've not been able to replicate this problem directly, though I think I can see logically how it might happen. I've just pushed dc0ef45a9b6a60be849b07d4061b45034a11638f which I think will fix it. Please let me know if it works.

If it doesn't work - it would be really handy to know, at the point in time when you get the exception what the values of SlowPeeker.blockPosition and resultingPosition are when the exception is thrown. You should be able to get this by running your harness in a debugger and breaking on AgentRunner line 297 which will give you stack when the exception happens.

**Comment by guoguanglei** [comment]
Hi, Richard

The fix does not work.
blockPosition actually is 0 and the resultingPosition varies when exception throws in every run.
The term buffer is default value.

```JAVA
java.lang.IllegalArgumentException: newPosition of 1429328256 out of range 49255424-116364288
        at io.aeron.Image.validatePosition(Image.java:664)
        at io.aeron.Image.position(Image.java:224)
        at uk.co.real_logic.artio.engine.framer.SlowPeeker.peek(SlowPeeker.java:49)
        at uk.co.real_logic.artio.engine.framer.SubscriptionSlowPeeker$LibrarySlowPeeker.peek(SubscriptionSlowPeeker.java:100)
        at uk.co.real_logic.artio.engine.framer.SubscriptionSlowPeeker.peek(SubscriptionSlowPeeker.java:43)
        at uk.co.real_logic.artio.engine.framer.Framer.sendOutboundMessages(Framer.java:349)
        at uk.co.real_logic.artio.engine.framer.Framer.doWork(Framer.java:299)
        at org.agrona.concurrent.AgentRunner.doDutyCycle(AgentRunner.java:268)
        at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:161)
        at java.lang.Thread.run(Thread.java:745)

count=1,firstTime=1541592327504,lastTime=1541592327504

java.lang.IllegalArgumentException: newPosition of 1429328256 out of range 49255424-116364288
        at io.aeron.Image.validatePosition(Image.java:664)
        at io.aeron.Image.position(Image.java:224)
        at uk.co.real_logic.artio.engine.framer.SlowPeeker.peek(SlowPeeker.java:49)
        at uk.co.real_logic.artio.engine.framer.SubscriptionSlowPeeker$LibrarySlowPeeker.peek(SubscriptionSlowPeeker.java:100)
        at uk.co.real_logic.artio.engine.framer.SubscriptionSlowPeeker.peek(SubscriptionSlowPeeker.java:43)
        at uk.co.real_logic.artio.engine.framer.Framer.sendOutboundMessages(Framer.java:349)
        at uk.co.real_logic.artio.engine.framer.Framer.doWork(Framer.java:299)
        at org.agrona.concurrent.AgentRunner.doDutyCycle(AgentRunner.java:268)
        at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:161)
        at java.lang.Thread.run(Thread.java:745)

count=6,firstTime=1541592327504,lastTime=1541592327506

java.lang.IllegalArgumentException: newPosition of 1429328256 out of range 49255424-116364288
        at io.aeron.Image.validatePosition(Image.java:664)
        at io.aeron.Image.position(Image.java:224)
        at uk.co.real_logic.artio.engine.framer.SlowPeeker.peek(SlowPeeker.java:49)
        at uk.co.real_logic.artio.engine.framer.SubscriptionSlowPeeker$LibrarySlowPeeker.peek(SubscriptionSlowPeeker.java:100)
        at uk.co.real_logic.artio.engine.framer.SubscriptionSlowPeeker.peek(SubscriptionSlowPeeker.java:43)
        at uk.co.real_logic.artio.engine.framer.Framer.sendOutboundMessages(Framer.java:349)
        at uk.co.real_logic.artio.engine.framer.Framer.doWork(Framer.java:299)
        at org.agrona.concurrent.AgentRunner.doDutyCycle(AgentRunner.java:268)
        at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:161)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by RichardWarburton** [comment]
Hi, thanks for looking into it. I think I need to recheck my assumptions around what Aeron is doing with this position value. Will revert when I can see what the issue is.

**Comment by RichardWarburton** [comment]
We've had a think about this case and have a few more questions:

1) Is the aeronChannel being used on the server it unicast UDP, multicast UDP or is it IPC?
2) This scenario could possibly happen if a long pause occurs between the call to controlledPeek and the set of position(). So can I confirm there's been no long (> 10 second) GC pauses here and that the machine that it's running on is well resourced. Ie has enough plenty of CPU cores and the Framer thread here isn't context switching off the machine. Another way of testing this might be to set the MediaDriver's clientLivenessTimeout() to a high value and see if this still happens.
3) If you can reproduce this easily when it happens can you use the Aeron Stat tool (https://github.com/real-logic/aeron/blob/master/aeron-samples/src/main/java/io/aeron/samples/AeronStat.java) to dump out the current values for the Aeron counters and post them here or send them to me so we can take a look? 
4) Finally - can I just check that whether you're using the Java or C Media Driver?

Sorry for not being able to get you an immediate solution on this one but I'm sure we'll get there.

**Comment by guoguanglei** [comment]
> We've had a think about this case and have a few more questions:
> 
> 1. Is the aeronChannel being used on the server it unicast UDP, multicast UDP or is it IPC?
> 2. This scenario could possibly happen if a long pause occurs between the call to controlledPeek and the set of position(). So can I confirm there's been no long (> 10 second) GC pauses here and that the machine that it's running on is well resourced. Ie has enough plenty of CPU cores and the Framer thread here isn't context switching off the machine. Another way of testing this might be to set the MediaDriver's clientLivenessTimeout() to a high value and see if this still happens.
> 3. If you can reproduce this easily when it happens can you use the Aeron Stat tool (https://github.com/real-logic/aeron/blob/master/aeron-samples/src/main/java/io/aeron/samples/AeronStat.java) to dump out the current values for the Aeron counters and post them here or send them to me so we can take a look?
> 4. Finally - can I just check that whether you're using the Java or C Media Driver?
> 
> Sorry for not being able to get you an immediate solution on this one but I'm sure we'll get there.

Thank you Richard. Our testing environment is unavailable currently, will try to gather the information needed once it is available.
1, The FIX server is using IPC. It is developed based on SampleServer.java in the artio-samples, change the aeron channel to IPC and framerIdleStrategy to BusySpinIdleStrategy. Other Artio internal configurations keep default.
    The FIX client is QuickFIX based.
2, The server is 16 cores CPU and 128G memory. we set memory to -Xmx32G.
    I will enable the GC log to see if there is long GC pause.
3, Will gather the aeron stat information. Most of the time the server will disconnect the client when the client become slow consumer. 
4, Embeded Java Media Driver.

**Comment by mjpt777** [comment]
It is worth noting the -Xmx32g would miss the opportunity to use compressed object pointers. You might want to consider -Xmx28g if that works for you.
