### ISSUE TITLE
ReplayIndexTest gets stuck on Windows

### ISSUE THREAD

**Issue by RichardWarburton** [real-logic/artio#198]

**Comment by mjpt777** [comment]
BTW this is intermittent.

**Comment by RichardWarburton** [comment]
org.junit.runners.model.TestTimedOutException: test timed out after 20000 milliseconds

	at java.lang.Thread.yield(Native Method)
	at uk.co.real_logic.artio.engine.logger.ReplayIndexTest.query(ReplayIndexTest.java:441)
	at uk.co.real_logic.artio.engine.logger.ReplayIndexTest.query(ReplayIndexTest.java:427)
	at uk.co.real_logic.artio.engine.logger.ReplayIndexTest.shouldQueryOverSequenceIndexBoundaries(ReplayIndexTest.java:254)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

**Comment by RichardWarburton** [comment]
@mjpt777 I'm stuggling to replicate this on a windows laptop. Was it a particularly fast machine? Which JDK version were you using?

**Comment by RichardWarburton** [comment]
Nevermind - I've managed to get the hang by running the test in a loop until it warms up on my laptop.

**Comment by RichardWarburton** [comment]
@mjpt777 I've fixed my reproduction of this issue, can you test it out on your machine and confirm that it's fixed?

**Comment by mjpt777** [comment]
Works now on my laptop.
