### ISSUE TITLE
Indexing bug when dealing with large messages

### ISSUE THREAD

**Issue by RichardWarburton** [real-logic/artio#206]
Sometimes, when working with long messages, we see the following error in Indexer: 

uk.co.real_logic.artio.util.AsciiEncodingException: 'D' isn't a valid digit @ 4161403
at uk.co.real_logic.artio.util.MutableAsciiBuffer.getDigit(MutableAsciiBuffer.java:152)
at uk.co.real_logic.artio.util.MutableAsciiBuffer.getDigit(MutableAsciiBuffer.java:
at uk.co.real_logic.artio.util.MutableAsciiBuffer.getInt(MutableAsciiBuffer.java:125)
at uk.co.real_logic.artio.decoder.HeaderDecoder.decode(HeaderDecoder.java:569)
at uk.co.real_logic.artio.engine.logger.SequenceNumberIndexWriter.onFragment(SequenceNumberIndexWriter.java:152)
at uk.co.real_logic.artio.engine.logger.Indexer.onFragment(Indexer.java:150)
at io.aeron.Image.controlledPoll(Image.java:344)
at io.aeron.Subscription.controlledPoll(Subscription.java:244)
at uk.co.real_logic.artio.engine.logger.Indexer.doWork(Indexer.java:71)
at org.agrona.concurrent.CompositeAgent.doWork(CompositeAgent.java:114)
at org.agrona.concurrent.CompositeAgent.doWork(CompositeAgent.java:114)
at org.agrona.concurrent.AgentRunner.doDutyCycle(AgentRunner.java:268)
at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:161)
at java.lang.Thread.run(Thread.java:748)

**Comment by stepan2271** [comment]
I believe the problem occurs when we try to parse tags of FIX message:
uk.co.real_logic.artio.engine.logger.SequenceNumberIndexWriter.onFragment(SequenceNumberIndexWriter.java:152),
while received only a fragment of this message.

**Comment by RichardWarburton** [comment]
Right - I've pushed a fix here. Please re-open if you spot an issue.
