### ISSUE TITLE
Should we wrap Indexer with ControlledFragmentAssembler? 

### ISSUE THREAD

**Issue by stepan2271** [real-logic/artio#207]
Sometimes, when working with long messages, we see the following error in Indexer: 

uk.co.real_logic.artio.util.AsciiEncodingException: 'D' isn't a valid digit @ 4161403
at uk.co.real_logic.artio.util.MutableAsciiBuffer.getDigit(MutableAsciiBuffer.java:152)
at uk.co.real_logic.artio.util.MutableAsciiBuffer.getDigit(MutableAsciiBuffer.java:
at uk.co.real_logic.artio.util.MutableAsciiBuffer.getInt(MutableAsciiBuffer.java:125)
at uk.co.real_logic.artio.decoder.HeaderDecoder.decode(HeaderDecoder.java:569)
at uk.co.real_logic.artio.engine.logger.SequenceNumberIndexWriter.onFragment(SequenceNumberIndexWriter.java:152)
at uk.co.real_logic.artio.engine.logger.Indexer.onFragment(Indexer.java:150)
at io.aeron.Image.controlledPoll(Image.java:344)
at io.aeron.Subscription.controlledPoll(Subscription.java:244)
at uk.co.real_logic.artio.engine.logger.Indexer.doWork(Indexer.java:71)
at org.agrona.concurrent.CompositeAgent.doWork(CompositeAgent.java:114)
at org.agrona.concurrent.CompositeAgent.doWork(CompositeAgent.java:114)
at org.agrona.concurrent.AgentRunner.doDutyCycle(AgentRunner.java:268)
at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:161)
at java.lang.Thread.run(Thread.java:748)

With previous versions of artio we also saw very similar problems trying to print archive (there were FIX messages with some 'binary noise' in the middle ). Now archiving changed and there is no problem with it. In one of your commits,
 (https://github.com/real-logic/artio/commit/ee3896422c35f06fbd50528942f8c8e3c7a5c601) you wrapped LogEntryHandler with FragmentAssembler. I believe that problem that we see in Indexer has the same nature.
Is there any reason why we don`t wrap Indexer with ControlledFragmentAssembler? I made the change, and seems like the problem disappeared.

**Comment by stepan2271** [comment]
I believe the problem occurs when we try to parse tags of FIX message:
uk.co.real_logic.artio.engine.logger.SequenceNumberIndexWriter.onFragment(SequenceNumberIndexWriter.java:152),
while received only a fragment of this message.
