### ISSUE TITLE
Replay Complete message not recevied

### ISSUE THREAD

**Issue by guoguanglei** [real-logic/artio#211]
When there is a replay happened after logon, the session will throw below exception when it is time to send the first heartbeat.
```Java
java.lang.IllegalStateException: Slow Consumer Disconnected conn=6284313389009898496,sess=1 @ time 1544695638619, Due to not being able to write since 1544695628618
	at uk.co.real_logic.artio.engine.framer.SenderEndPoint.checkTimeouts(SenderEndPoint.java:443)
	at uk.co.real_logic.artio.engine.framer.SenderEndPoints.checkTimeouts(SenderEndPoints.java:192)
	at uk.co.real_logic.artio.engine.framer.Framer.doWork(Framer.java:310)
	at org.agrona.concurrent.AgentRunner.doDutyCycle(AgentRunner.java:268)
	at org.agrona.concurrent.AgentRunner.run(AgentRunner.java:161)
	at java.lang.Thread.run(Thread.java:748)
```
Seems because the Replay Complete message never published because of missing bufferClaim.commit() at below location?

https://github.com/real-logic/artio/blob/edd0e83df0579e9925d007a7e186d37f11e6f684/artio-core/src/main/java/uk/co/real_logic/artio/engine/logger/ReplayerSession.java#L372

**Comment by RichardWarburton** [comment]
Thanks for reporting @guoguanglei - I've improved the testing to catch this kind of regression as well.
