### ISSUE TITLE
"Unknown recording" error from archive with enabled persistent logs

### ISSUE THREAD

**Issue by melodi-c** [real-logic/artio#247]
How to reproduce on example_exchange/example_buyer

1. enable logInboundMessages and logOutboundMessages  and comment line with cleanupLogs in in ExchangeApplication class https://gist.github.com/melodi-c/f6e674692c8ff05a04b6fc34a4713cd5
2. Launch ExchangeApplication and BuyerApplication
3. Stop ExchangeApplication and BuyerApplication
4. Again launch ExchangeApplication and you have two exceptions
```
io.aeron.archive.client.ArchiveException: response for correlationId=22, error: unknown recording 1
	at io.aeron.archive.client.AeronArchive.pollForResponse(AeronArchive.java:1076)
	at io.aeron.archive.client.AeronArchive.getStopPosition(AeronArchive.java:929)
	at uk.co.real_logic.artio.engine.logger.Indexer.lambda$catchIndexUp$0(Indexer.java:90)
	at uk.co.real_logic.artio.engine.logger.IndexedPositionReader.readLastPosition(IndexedPositionReader.java:108)
	at uk.co.real_logic.artio.engine.logger.ReplayIndex.readLastPosition(ReplayIndex.java:175)
	at uk.co.real_logic.artio.engine.logger.Indexer.catchIndexUp(Indexer.java:86)
	at uk.co.real_logic.artio.engine.logger.Indexer.<init>(Indexer.java:69)
	at uk.co.real_logic.artio.engine.EngineContext.newIndexers(EngineContext.java:218)
	at uk.co.real_logic.artio.engine.EngineContext.newArchivingAgent(EngineContext.java:247)
	at uk.co.real_logic.artio.engine.EngineContext.<init>(EngineContext.java:104)
	at uk.co.real_logic.artio.engine.FixEngine.<init>(FixEngine.java:170)
	at uk.co.real_logic.artio.engine.FixEngine.launch(FixEngine.java:75)
	at uk.co.real_logic.artio.example_exchange.ExchangeApplication.main(ExchangeApplication.java:68)
```
```
io.aeron.archive.client.ArchiveException: response for correlationId=24, error: unknown recording 3
	at io.aeron.archive.client.AeronArchive.pollForResponse(AeronArchive.java:1076)
	at io.aeron.archive.client.AeronArchive.getStopPosition(AeronArchive.java:929)
	at uk.co.real_logic.artio.engine.logger.Indexer.lambda$catchIndexUp$0(Indexer.java:90)
	at uk.co.real_logic.artio.engine.logger.IndexedPositionReader.readLastPosition(IndexedPositionReader.java:108)
	at uk.co.real_logic.artio.engine.logger.ReplayIndex.readLastPosition(ReplayIndex.java:175)
	at uk.co.real_logic.artio.engine.logger.Indexer.catchIndexUp(Indexer.java:86)
	at uk.co.real_logic.artio.engine.logger.Indexer.<init>(Indexer.java:69)
	at uk.co.real_logic.artio.engine.EngineContext.newIndexers(EngineContext.java:240)
	at uk.co.real_logic.artio.engine.EngineContext.newArchivingAgent(EngineContext.java:247)
	at uk.co.real_logic.artio.engine.EngineContext.<init>(EngineContext.java:104)
	at uk.co.real_logic.artio.engine.FixEngine.<init>(FixEngine.java:170)
	at uk.co.real_logic.artio.engine.FixEngine.launch(FixEngine.java:75)
	at uk.co.real_logic.artio.example_exchange.ExchangeApplication.main(ExchangeApplication.java:68)
```

**Comment by RichardWarburton** [comment]
Closing issue as you've said this was a user error on the gitter chat. Please re-open if you still think there's a genuine bug.
