### ISSUE TITLE
FixMessageLogger stops logging and buffered every message

### ISSUE THREAD

**Issue by rpachon** [real-logic/artio#408]
Hello,

It looks like FixMessageLogger logs a few message and then it begins to buffered every messages.

It seems that something goes wrong with Timestamp and at a point maxTimestampToHandle stays locked in the past.

Finally messages are logged on shutdown when buffer is flushed.

**Comment by RichardWarburton** [comment]
Which version of Artio are you using?

**Comment by rpachon** [comment]
With 0.79 Logging was broken so I update to 0.80 this morning.
Logging is back but with this issue.

**Comment by RichardWarburton** [comment]
A few questions to try and narrow this down:

 * Have you got consistent EpochNanoClocks set?
 * Are messages consistently being sent across FIX connections normally?
 * Does maxTimestampToHandle get locked at a reasonable time - ie during the duration of the run?
 * When messages are logged on shutdown are they both received and sent or just one direction?

**Comment by rpachon** [comment]
Hello,

I have 2 process, one is a Quickfix acceptor and a Artio initiator. There are connected sending fix message across a normal FIX connection. 
In Artio I use the default EpochNanoClocks:
```java
		configuration = new EngineConfiguration()
				.libraryAeronChannel(IPC_CHANNEL)
				.monitoringFile(dataDirName + File.separator + "fix-engine/monitoring" + File.separator + "engineCounters")
				.logFileDir(dataDirName + File.separator + "fix-engine/logs")
				.logInboundMessages(true)
				.logOutboundMessages(true);

		configuration.aeronArchiveContext()
				.aeronDirectoryName(aeronConfig.getAeronDirName())
				.controlRequestChannel(aeronConfig.getAeronControlRequest())
				.controlResponseChannel(aeronConfig.getAeronControlResponse());

		configuration.aeronContext()
				.aeronDirectoryName(aeronConfig.getAeronDirName());
```
Here are the log of the full starting sequence. I always log through StreamTimestampZipper$LogEntryHandler.onBufferedMessage

```log
timestamlp: 1603784345083768784 | maxTimestampToHandle: 0
timestamlp: 1603784345086081384 | maxTimestampToHandle: 0
Breakpoint reached at uk.co.real_logic.artio.engine.logger.StreamTimestampZipper$LogEntryHandler.onBufferedMessage(StreamTimestampZipper.java:375)
Breakpoint reached at uk.co.real_logic.artio.engine.logger.StreamTimestampZipper$LogEntryHandler.onBufferedMessage(StreamTimestampZipper.java:389)
Fix message logged
Breakpoint reached at uk.co.real_logic.artio.engine.logger.StreamTimestampZipper$LogEntryHandler.onBufferedMessage(StreamTimestampZipper.java:375)
Breakpoint reached at uk.co.real_logic.artio.engine.logger.StreamTimestampZipper$LogEntryHandler.onBufferedMessage(StreamTimestampZipper.java:389)
Fix message logged
Breakpoint reached at uk.co.real_logic.artio.engine.logger.StreamTimestampZipper$LogEntryHandler.onBufferedMessage(StreamTimestampZipper.java:375)
Breakpoint reached at uk.co.real_logic.artio.engine.logger.StreamTimestampZipper$LogEntryHandler.onBufferedMessage(StreamTimestampZipper.java:389)
Fix message logged
timestamlp: 1603784353083726763 | maxTimestampToHandle: 1603784345086081384
Breakpoint reached at uk.co.real_logic.artio.engine.logger.StreamTimestampZipper$LogEntryHandler.onBufferedMessage(StreamTimestampZipper.java:375)
Breakpoint reached at uk.co.real_logic.artio.engine.logger.StreamTimestampZipper$LogEntryHandler.onBufferedMessage(StreamTimestampZipper.java:389)
Fix message logged
And no more fix message logged
-----

And then timestamps are locked:
LogEntryHandler.onFragment -> if (templateId == FixMessageDecoder.TEMPLATE_ID) -> if (timestamp <= maxTimestampToHandle)
timestamlp: 1603784385370784481 | maxTimestampToHandle: 1603784345740665746

StreamTimestampZipper.processReorderBuffer -> if (timestamp <= minHandleTimestamp)
timestamp: 1603784353083726763 | minHandleTimestamp:1603784345740665746
```
And finally messages are logged in both way (in and out).

**Comment by rpachon** [comment]
An other point I forgot to mention is that our fix connector daemon is using Artio to connect to X markets and Aeron to communicate with the rest of our system.
Artio and Aeron are sharing the same driver. Could it be an issue ?

**Comment by RichardWarburton** [comment]
So I've tried to reproduce your issue in https://github.com/real-logic/artio/commit/f617566a84984faa39c519ae1a682d13739b5aaa#diff-48fa8e0803f888997c36f5171d17390f544bfbb7291b16a1ef1737b1e67f966aR175 , but the logger seemed not to stall. Can you log the timestamp of /all/ messages that you receive including a few after the point at which your system stops logging messages? And in this log line can you also log the streamId() and sessionId() of the message?

**Comment by rpachon** [comment]
Thank you for your help:
```log
maxTimestampToHandle: 0 | Message timestamp: 1603800570460284857 | sessionId: 1 | streamId: 2
maxTimestampToHandle: 0 | Message timestamp: 1603800570513023097 | sessionId: 1 | streamId: 1
OK: 8=FIX.4.29=7435=A34=1 ... 10=088
maxTimestampToHandle: 1603800570513023097 | Message timestamp: 1603800578520566892 | sessionId: 1 | streamId: 2
OK: 8=FIX.4.29=6835=A34=1 ... 10=056
maxTimestampToHandle: 1603800571498664415 | Message timestamp: 1603800581079423921 | sessionId: 1 | streamId: 1
maxTimestampToHandle: 1603800571498664415 | Message timestamp: 1603800586520278849 | sessionId: 1 | streamId: 2
maxTimestampToHandle: 1603800571498664415 | Message timestamp: 1603800591079715485 | sessionId: 1 | streamId: 1
maxTimestampToHandle: 1603800571498664415 | Message timestamp: 1603800594520749164 | sessionId: 1 | streamId: 2
maxTimestampToHandle: 1603800571498664415 | Message timestamp: 1603800601079324665 | sessionId: 1 | streamId: 1
maxTimestampToHandle: 1603800571498664415 | Message timestamp: 1603800602520212943 | sessionId: 1 | streamId: 2

-- shutdown signal send -- 

OK: 8=FIX.4.29=5635=0 ... 10=012
OK: 8=FIX.4.29=5635=0 ... 10=014
OK: 8=FIX.4.29=5635=0 ... 10=012
OK: 8=FIX.4.29=5635=0 ... 10=016
OK: 8=FIX.4.29=5635=0 ... 10=012
OK: 8=FIX.4.29=5635=0 ... 10=004
OK: 8=FIX.4.29=5635=0 ... 10=254
OK: 8=FIX.4.29=5635=0 ... 10=006
OK: 8=FIX.4.29=5635=5 ... 10=018

Process finished with exit code 130 (interrupted by signal 2: SIGINT)

```

**Comment by rpachon** [comment]
I had the message timestamp received from the SessionHandler to compare. 
```log
maxTimestampToHandle: 0 | Message timestamp: 1603803621412591705 | sessionId: 1 | streamId: 2
maxTimestampToHandle: 0 | Message timestamp: 1603803621467322806 | sessionId: 1 | streamId: 1
Message Timestamp from SessionHandler: 4411614489711817779
OK: 8=FIX.4.29=7435=A49=SWISSQ_T56=UBS_T34=152=20201027-13:00:21.41298=0108=10141=N10=069
maxTimestampToHandle: 1603803621467322806 | Message timestamp: 1603803629473659005 | sessionId: 1 | streamId: 2
OK: 8=FIX.4.29=6835=A34=149=UBS_T52=20201027-13:00:21.43256=SWISSQ_T98=0108=1010=040
Message Timestamp from SessionHandler: 4411614489728594995
maxTimestampToHandle: 1603803622533771678 | Message timestamp: 1603803631704406858 | sessionId: 1 | streamId: 1
maxTimestampToHandle: 1603803622533771678 | Message timestamp: 1603803637473487127 | sessionId: 1 | streamId: 2
Message Timestamp from SessionHandler: 4411614489745372211
maxTimestampToHandle: 1603803622533771678 | Message timestamp: 1603803641705208527 | sessionId: 1 | streamId: 1
maxTimestampToHandle: 1603803622533771678 | Message timestamp: 1603803645474024848 | sessionId: 1 | streamId: 2
Message Timestamp from SessionHandler: 4411614489762149427
maxTimestampToHandle: 1603803622533771678 | Message timestamp: 1603803651704534452 | sessionId: 1 | streamId: 1
maxTimestampToHandle: 1603803622533771678 | Message timestamp: 1603803653474123228 | sessionId: 1 | streamId: 2
```
