### ISSUE TITLE
FakeHandler.lastMessage() fails if buffer exceeds 128 bytes

### ISSUE THREAD

**Issue by mwong38** [real-logic/artio#422]
## How to reproduce:

In `uk.co.real_logic.artio.system_tests.MessageBasedInitiatorSystemTest`, edit `sendInvalidExecutionReport` so that the buffer would exceed 128 bytes. For example:
```
        executionReportEncoder
            .orderID("order            ")  // add more than 5 spaces and it would easily exceed 128 bytes
            .execID("exec")
            .execType('5') // Invalid exec type
            .ordStatus(OrdStatus.FILLED)
            .side(Side.BUY);
```

Run `shouldValidateMissingEnumValue` test which uses `handler.lastMessage()` and it will throw exception:
```
index=128 capacity=128
java.lang.IndexOutOfBoundsException: index=128 capacity=128
	at org.agrona.concurrent.UnsafeBuffer.boundsCheck(UnsafeBuffer.java:1721)
	at org.agrona.concurrent.UnsafeBuffer.getByte(UnsafeBuffer.java:801)
	at uk.co.real_logic.artio.util.MutableAsciiBuffer.scan(MutableAsciiBuffer.java:223)
	at uk.co.real_logic.artio.util.MutableAsciiBuffer.scan(MutableAsciiBuffer.java:215)
	at uk.co.real_logic.artio.decoder.HeaderDecoder.decode(HeaderDecoder.java:590)
	at uk.co.real_logic.artio.decoder.ExecutionReportDecoder.decode(ExecutionReportDecoder.java:355)
	at uk.co.real_logic.artio.system_tests.MessageBasedInitiatorSystemTest.shouldValidateMissingEnumValue(MessageBasedInitiatorSystemTest.java:152)
```

## Reason
I think the reason is the underlying `FakeHandler.lastMessageBuffer` uses an `ExpandableArrayBuffer` which defaults to 128 bytes of capacity. 

## Fix
I think the solution is to re-wrap `lastMessage` to `lastMessageBuffer` upon copying on each call to `onMessage` so that it will update the reference to the underlying byteArray and capacity.

**Comment by RichardWarburton** [comment]
Thanks Michael - good spot.
