### ISSUE TITLE
FixArchivePrinter 0.137 incompatible with Aeron 1.40

### ISSUE THREAD

**Issue by pcdv** [real-logic/artio#468]
```
io.aeron.exceptions.ConfigurationException: ERROR - AeronArchive.Context.controlResponseChannel must be set
	at io.aeron.archive.client.AeronArchive$Context.conclude(AeronArchive.java:2883)
	at io.aeron.archive.client.AeronArchive.connect(AeronArchive.java:226)
	at uk.co.real_logic.artio.engine.logger.FixArchiveScanner.<init>(FixArchiveScanner.java:215)
	at uk.co.real_logic.artio.engine.logger.FixArchivePrinter.scanArchive(FixArchivePrinter.java:239)
	at uk.co.real_logic.artio.engine.logger.FixArchivePrinter.scan(FixArchivePrinter.java:76)
	at uk.co.real_logic.artio.engine.logger.FixArchivePrinter.main(FixArchivePrinter.java:52)
```
Workaround: set system property `aeron.archive.control.response.channel` to some value

**Comment by RichardWarburton** [comment]
Hi Paul,

I've pushed a quick fix for this, please let me know if it works ok in your setup.

**Comment by pcdv** [comment]
Hi Richard,

Thanks, that will do it, I think. I will check once the fix is included in an official release. This is not urgent as there is a workaround.

**Comment by pcdv** [comment]
It took me a while to finally test it.

The fix is not ideal because it became impossible to override the hardcoded control response channel (with a system property) in case there is a conflict with another process:

```
io.aeron.exceptions.RegistrationException: ERROR - io.aeron.exceptions.AeronException : ERROR - channel error - Address already in use (at sun.nio.ch.Net.bind0(Native Method)): aeron:udp?term-length=65536|sparse=true|mtu=1408|endpoint=localhost:8010, errorCodeValue=11
	at io.aeron.ClientConductor.onError(ClientConductor.java:229)
	at io.aeron.DriverEventsAdapter.onMessage(DriverEventsAdapter.java:115)
	at org.agrona.concurrent.broadcast.CopyBroadcastReceiver.receive(CopyBroadcastReceiver.java:116)
	at io.aeron.DriverEventsAdapter.receive(DriverEventsAdapter.java:68)
	at io.aeron.ClientConductor.service(ClientConductor.java:1252)
	at io.aeron.ClientConductor.awaitResponse(ClientConductor.java:1310)
	at io.aeron.ClientConductor.addSubscription(ClientConductor.java:659)
	at io.aeron.ClientConductor.addSubscription(ClientConductor.java:634)
	at io.aeron.Aeron.addSubscription(Aeron.java:365)
	at io.aeron.archive.client.AeronArchive.connect(AeronArchive.java:229)
	at uk.co.real_logic.artio.engine.logger.FixArchiveScanner.<init>(FixArchiveScanner.java:217)
	at uk.co.real_logic.artio.engine.logger.FixArchivePrinter.scanArchive(FixArchivePrinter.java:239)
	at uk.co.real_logic.artio.engine.logger.FixArchivePrinter.scan(FixArchivePrinter.java:76)
	at uk.co.real_logic.artio.engine.logger.FixArchivePrinter.main(FixArchivePrinter.java:52)
```
But this is minor since the problem happens in an automated test which can be modified to not use FixArchivePrinter.

Regards.
