### ISSUE TITLE
Failed: ClusteredGatewaySystemTest.shouldExchangeMessagesInCluster

### ISSUE THREAD

**Issue by mjpt777** [real-logic/artio#95]
This happened on Linux.

```
arrays first differed at element [7553041]; expected:&lt;6&gt; but was:&lt;7&gt;
    at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:55)
    at org.junit.Assert.internalArrayEquals(Assert.java:532)
    at org.junit.Assert.assertArrayEquals(Assert.java:341)
    at org.junit.Assert.assertArrayEquals(Assert.java:352)
    at uk.co.real_logic.fix_gateway.system_tests.ClusteredGatewaySystemTest.assertFilesEqual(ClusteredGatewaySystemTest.java:305)
    at uk.co.real_logic.fix_gateway.system_tests.ClusteredGatewaySystemTest.lambda$allClusterNodesHaveSameIndexFiles$5(ClusteredGatewaySystemTest.java:283)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
    at java.util.stream.SliceOps$1$1.accept(SliceOps.java:204)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
    at uk.co.real_logic.fix_gateway.system_tests.ClusteredGatewaySystemTest.allClusterNodesHaveSameIndexFiles(ClusteredGatewaySystemTest.java:278)
    at uk.co.real_logic.fix_gateway.system_tests.ClusteredGatewaySystemTest.shouldExchangeMessagesInCluster(ClusteredGatewaySystemTest.java:142)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
    at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.AssertionError: expected:&lt;6&gt; but was:&lt;7&gt;
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:834)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:144)
    at org.junit.internal.ExactComparisonCriteria.assertElementsEqual(ExactComparisonCriteria.java:8)
    at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:53)
    ... 30 more
```

**Comment by RichardWarburton** [comment]
Closing issue as old clustering removed for now.
